# Generated by Django 5.1.7 on 2025-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
